# Generated by Django 5.0.7 on 2024-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordChannels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("polls", models.BigIntegerField(blank=True, null=True)),
                ("queues", models.BigIntegerField(blank=True, null=True)),
                ("chat", models.BigIntegerField(blank=True, null=True)),
                ("queue_counter", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
