# Generated by Django 5.0.7 on 2024-07-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_discordchannels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discordchannels",
            name="polls",
        ),
    ]
