# Generated by Django 5.0.7 on 2024-07-23 21:22

import annoying.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_remove_discordchannels_polls"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="roles",
            field=annoying.fields.AutoOneToOneField(
                default=1, on_delete=django.db.models.deletion.DO_NOTHING, to="bot.rolespreference"
            ),
            preserve_default=False,
        ),
    ]
