# Generated by Django 5.0.7 on 2024-07-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_player_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queueplayer",
            name="player",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot.player"),
        ),
        migrations.AlterField(
            model_name="queueplayer",
            name="queue",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot.ladderqueue"),
        ),
    ]
