# Generated by Django 5.0.7 on 2024-07-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_queueplayer_player_alter_queueplayer_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("value", models.SmallIntegerField(choices=[(1, "Positive"), (-1, "Negative")])),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                (
                    "from_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report_from", to="bot.player"
                    ),
                ),
                ("match", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bot.match")),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report_to", to="bot.player"
                    ),
                ),
            ],
            options={
                "unique_together": {("from_player", "to_player", "match")},
            },
        ),
    ]
