FROM mcr.microsoft.com/devcontainers/python:1-3.12-bookworm

ENV PYTHONUNBUFFERED 1

RUN apt update && apt install make protobuf-compiler vim -y

# ENV DB_NAME=asdf
# ENV DB_USER=asdf
# ENV DB_PW=asdf
# ENV DB_HOST=db
# ENV DB_PORT=3306
